export { default as CV_ICON } from './cv-icon.png';
export { default as CYBER_SECURITY } from './cyber-security-icon.png';
export { default as DATA_ANALYTICS } from './data-analytics-icon.png';
export { default as FOOTER_LOGO } from './footer-logo.png';
export { default as HER0_IMG } from './hero-img.png';
export { default as INSTRUCTOR_IMG } from './instructor-frame.png';
export { default as INTERNSHIP_ICON } from './internship-icon.png';
export { default as MENTORSHIP_ICON } from './mentorship-icon.png';
export { default as PROJECT_ICON } from './project-icon.png';
export { default as SCRUM_ICON } from './scrum-icon.png';
export { default as SOCIALS_ICON } from './social-imgs.png';
export { default as STARS_ICONS } from './star-image.png';
export { default as TECHTITUDE_LOGO } from './techtitude-logo.png';
export { default as UIUX_ICON } from './uiux-icon.png';
export { default as ELLIPSE } from './ellipse.png'
//Mobile Images
export { default as MOBILE_BUSINESS_ICON } from './mobile-imgs/business-logo.png'
export { default as MOBILE_SCRUM_ICON } from './mobile-imgs/scrum-logo.png'
export { default as MOBILE_UIUX_ICON } from './mobile-imgs/uiux-logo.png'
export { default as MOBILE_CYBER_SECURITY } from './mobile-imgs/mobile-cyber-security.png'
export { default as NAV_ICON } from './nav-icon.png'